const NavigationRoutes = {
  AUTH_STACK: {
    LOGIN: 'LOGIN_SCREEN',
    SIGNUP: 'SIGNUP_SCREEN',
    PLAYER_SELECTION:'PLAYER_SELECTION_SCREEN'
  },
  APP_STACK: {
    BOTTOM_TABS: 'BOTTOM_TABS',
    HOME: 'HOME_SCREEN',
    PROFILE: 'PROFILE',
    TIERS:'TIERS',
    REWARDS:'REWARDS',
    PLAYER_SELECTION:'PLAYER_SELECTION',
    ACCOUNTS:'ACCOUNTS',
    ACTIVITY:'ACTIVITY'
  },
};

export default NavigationRoutes;
