const NavigationRoutes = {
  AUTH_STACK: {
    LOGIN: 'LOGIN_SCREEN',
    FORGET_PASSWORD: 'FORGET_PASSWORD_SCREEN',
    SIGNUP: 'SIGNUP_SCREEN',
    PLAYER_SELECTION:'PLAYER_SELECTION_SCREEN'
  },
  APP_STACK: {
    BOTTOM_TABS: 'BOTTOM_TABS',
    HOME: 'HOME_SCREEN',
    PROFILE: 'PROFILE',
    TIERS:'TIERS',
    REWARDS:'REWARDS',
    PLAYER_SELECTION:'PLAYER_SELECTION',
    ACCOUNTS:'ACCOUNTS',
    ACTIVITY:'ACTIVITY',
    PERFORMANCE:'PERFORMANCE',
    PAYMENT:'PAYMENT',
    PROFILE_SETTING: "PROFILE_SETTING",
    ABOUT: "ABOUT",
    ALL_PERFORMANCE: "ALL_PERFORMANCE",
    ANNOUNCEMENT:"ANNOUNCEMENT",
    FAQS:"FAQS",
    COACH_HOME: "COACH_HOME"
  },
};

export default NavigationRoutes;
